package com.exam;

import java.util.List;

import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.stereotype.Service;
import org.springframework.web.bind.annotation.ResponseBody;

@Service
public class UserServiceHB {
	// This means to get the bean called userRepository
	// Which is auto-generated by Spring, we will use it to handle the data
	@Autowired
	private UserDao userDao;

	public @ResponseBody String seveUser(User user) {
		User ret = userDao.save(user);
		return "saved";
	}

	public @ResponseBody User updateUser(User user) {
		User u = userDao.update(user);
		return u;
	}

	public @ResponseBody User deleteUser(Integer id) {
		User user = userDao.delete(new User(id));
		return user;
	}

	// public @ResponseBody List<User> showAllUsers() {
	public List<User> showAllUsers() {
		// This returns a JSON or XML with the users
		List<User> users = userDao.showAll();
		return users;
	}

	public @ResponseBody User showUserById(Integer id) {
		User user = userDao.showById(id).get(0);
		return user;
	}

	public @ResponseBody Iterable<User> showUserByName(String name) {
		User u = new User();
		u.setName(name);
		Iterable<User> users = userDao.showByName(u);
		return users;
	}

}
